# kubeseal --format yaml < .k8s/database/secrets.yaml > .k8s/database/sealed-secrets.yaml
# kubectl apply -f .k8s/database/sealed-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: services
type: Opaque
stringData:
  AUTH_DB_URL: postgres://<user>:<password>@postgres-service.databases.svc.cluster.local:5432/auth?sslmode=disable