
server:
  dev:
    enabled: false
  ha:
    enabled: true
    replicas: 3
  auditStorage:
    enabled: true
  storage:
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 0    
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/certs/tls.crt"
          tls_key_file = "/vault/certs/tls.key"
        }
        storage "raft" {
          path = "/vault/data"
          node_id = "vault-{{ pod }}"  # Usa o nome do Pod como node_id
        }
        service_registration "kubernetes" {}

resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "500m"

ui:
  enabled: true
  service:
    type: ClusterIP

auth:
  - type: kubernetes
    roles:
      - name: default
        bound_service_account_names: "*"
        bound_service_account_namespaces: "*"
        policies: default
