server:
  dev:
    enabled: false
  ha:
    enabled: true
    replicas: 1
  auditStorage:
    enabled: true
  storage:
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/certs/tls.crt"
          tls_key_file = "/vault/certs/tls.key"
        }
        storage "raft" {
          path = "/vault/data"
          node_id = "vault-{{ pod }}"
        }
        service_registration "kubernetes" {}
ui:
  enabled: true
injector:
  enabled: true