# kubectl create namespace databases
# kubectl apply -f sealed-postgres-secret.yaml
# kubectl apply -f postgres-pvc.yaml
# kubectl apply -f postgres-deployment.yaml
# kubectl apply -f postgres-service.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc