apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.bitnami.com/bitnami"
    chart: postgresql
    targetRevision: 16.6.3
    helm:
      values: |
        persistence:
          enabled: true
          size: 512Mi
        auth:
          existingSecret: postgresql-auth
          secretKeys:
            adminPasswordKey: postgres-password
  destination:
    server: "https://kubernetes.default.svc"
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true