# kubeseal --format yaml < .k8s/auth-service/db/postgres-secrets.yaml > .k8s/auth-service/db/postgres-sealed-secrets.yaml
# kubectl apply -f .k8s/auth-service/db/postgres-sealed-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: postgresql-auth
  namespace: databases
type: Opaque
stringData:
  postgres-password: <postgres-password>
