apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres-secret
  namespace: databases
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBQcTT89Bam932nYYGg/h1ao9TitVKskKQbjngwHJdyyI7GcPV1AtroZuyEo2M45GL9xFylR4dOTeQqfxtoSK18D4UkxUKcjwvETE3A2+uGLtAzefdPI3Zx9filndKi7irQjJ2uKGY1JK63LzjYuJqTZ+VnAJOivp39v6xt8JmGWnAvCZs4M/eXW01qBtKwxpa2QkvN1eB0d7xcbWRhml3ZLvlojnDlzL8/g3RNKaJSMEEz+djIM1oIhiGjcAZoLYRWNf51kkXL2LwRGZR/tHXdMi+j3XEUotB6PKDWRop21bWusgd3MDQFjzg9VL1iLu+qBIqY8BDd0KxGBwzp2eEqp6uLZbk9V2JQvZUzTWav5xUL4iYyInBPBAmxUugXz9Q25YolWGJDZ386+4myjsYkyonmaQmwr5tmyIH1LglqV4bz0eT0oBpN4VLhrcLthMh2QfVZHzlOGtS4/ORqfOY1j/12F2P2Kpm4DPhKEUXxc7agb3EjgPP9z0CFgLfLcxkKmcw0+6m1qafgT4ymJmuoHAydjLoItnwFKa1hnG2Su+LqJR1vCGHysDVdjdpYGlFvz4dyQ/FPUEd3ie0HnuALrxdpASdKNMZxJ3xZX5ant5vYpbhTF56AXmzTfWOpdizmJmw5uFxIetMEggv+UU1VOEGnDthT9TPckdu67L0ffuW0+KNHzTaqSWCH11noQ3MmIAFqvrX4ihUW/yF1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres-secret
      namespace: databases
    type: Opaque

