apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels: 
    app: auth-service
  namespace: services
data:
  PORT: "8080"
  ENVIRONMENT: "production"
  ACCESS_JWT_EXPIRATION: "3600"
  REFRESH_JWT_EXPIRATION: "604800"