apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels: 
    app: auth-service
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: hoyci98/auth-service:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets 
                  key: DATABASE_URL
            - name: PRIVATE_KEY_ACCESS
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: PRIVATE_KEY_ACCESS
            - name: PRIVATE_KEY_REFRESH
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: PRIVATE_KEY_REFRESH 
            - name: PUBLIC_KEY_ACCESS
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: PUBLIC_KEY_ACCESS
            - name: PUBLIC_KEY_REFRESH
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: PUBLIC_KEY_REFRESH
            - name: ACCESS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: ACCESS_JWT_SECRET
            - name: REFRESH_JWT_SECRET  
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: REFRESH_JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENVIRONMENT
            - name: ACCESS_JWT_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ACCESS_JWT_EXPIRATION
            - name: REFRESH_JWT_EXPIRATION  
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REFRESH_JWT_EXPIRATION
          volumeMounts:
            - name: secrets-volume
              mountPath: "/secrets"
      volumes:
        - name: secrets-volume
          secret:
            secretName: auth-service-secrets