# kubeseal --format yaml < .k8s/secrets/secrets.yaml > .k8s/secrets/sealed-secrets.yaml
# kubectl apply -f .k8s/secrets/sealed-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: services
type: Opaque
data:
  PRIVATE_KEY_ACCESS: BASE64_XPTO
  PRIVATE_KEY_REFRESH: BASE64_XPTO
  PUBLIC_KEY_ACCESS: BASE54_XPTO
  PUBLIC_KEY_REFRESH: BASE64_XPTO
  ACCESS_JWT_SECRET: BASE64_XPTO
  REFRESH_JWT_SECRET: BASE64_XPTO
  DATABASE_URL: BASE64_XPTO
