name: Deploy API Gateway

on:
  push:
    paths:
      - 'api-gateway/**'
    branches:
      - main

env:
  IMAGE_NAME: your-dockerhub-user/api-gateway
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG ./api-gateway

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Sync ArgoCD
        run: |
          argocd login argocd.whoam.site --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app sync api-gateway-app