name: Configure Vault Roles

on:
  push:
    paths:
      - '.k8s/vault/roles/**'

jobs:
  configure-roles:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Role Setup Script
        env:
          VAULT_ROOT_TOKEN: ${{ secrets.VAULT_ROOT_TOKEN }}
        run: |
          cd .k8s/vault/roles
          chmod +x setup-vault-roles.sh
          ./setup-vault-roles.sh