basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API para gestão de usuário e autenticação
  title: Auth Service API dwada
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
